#!/usr/bin/env bash
# Script will display information about subdomains.

display_info() {
	local domain="$1"
	local subdomain="$2"
	local record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $4; }')
	local dist=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $5; }')
	echo "The subdomain $subdomain is a $record_type record and points to $dist"
}
domain="$1"

if [ "$#" -eq 1 ]; then
	display_info "$domain" "www"
	display_info "$domain" "lb-01"
	display_info "$domain" "web-01"
	display_info "$domain" "web-02"
else
	subdomain="$2"
	display_info "$domain" "$subdomain"
fi
