#!/usr/bin/env bash
#install nginx in my server
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx reload
