#!/usr/bin/env bash
# script to configure new ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello World!" > /var/www/html/index.html

# redirection
string_to_replace="location /redirect_me/ {\n\treturn 301 https://google.com/;\n}"
sudo sed -i "/server_name _;/a $string_to_replace" /etc/nginx/sites-enabled/default

sudo service nginx restart
