#!/usr/bin/env bash
# script to configure new ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello World!" > /var/www/html/index.html

# redirection
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
