#!/usr/bin/env bash
# changing to 404 page not found

sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello World!" > /var/www/html/index.html

# redirection
string_to_replace="location /redirect_me/ {\n\treturn 301 https://google.com/;\n}"
sudo sed -i "/server_name _;/a $string_to_replace" /etc/nginx/sites-enabled/default

#creating 404 page not found
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_sever;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
