#!/usr/bin/env bash
# This script:
# -creates the file /var/run/myscript.pid containing its PID
# -displays "To infinity and beyond" indefinitely
# -displays "I hate the kill command" when receiving a SIGTERM signal
#-displays "Y U no love me?!" when receiving a SIGINT signal
#-deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid" SIGTERM
trap "echo 'Y u no love me?!'" SIGINT
trap "rm /var/run/myscript.pid" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
