#!/usr/bin/env bash
# This script displays "To infinity and beyond" and sleeps for 2 sec after each
# iteration and I am invincible!!! when receiving a SIGTERM signal.
while true
do
    echo "To infinity and beyond"
    trap "echo I am invincible!!!" SIGTERM
    sleep 2
done
