#!/usr/bin/env bash
# This script displays 1-20 with superstitions from China, Japan and Italy.
i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
        ((i++))
done
